name: Build
on: [push]

jobs:
  build:
    name: "David's Build"
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'gradlew build'
        run: cd ${GITHUB_WORKSPACE} && ./gradlew build
